name: ElytraOnSpawn
version: '1.3'
main: de.questcraft.plugins.elytraOnSpawn
api-version: '1.21'
commands:
  elytraOnSpawn:
    description: Configure elytraOnSpawn settings
    usage: /elytraOnSpawn <subcommand>